# Generated by Django 3.1.5 on 2021-01-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
