# Generated by Django 3.1.5 on 2021-01-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='upload',
            new_name='image',
        ),
    ]
