# Generated by Django 2.1.15 on 2021-03-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0003_backgrounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='backgrounds',
            name='back_img',
            field=models.ImageField(default='default.jpg', upload_to='background_pics/'),
        ),
    ]
